name: Deploy to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name fcl-eks-cluster \
            --region us-east-1

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./secret.yml
          kubectl apply -f ./db-pvc.yml
          kubectl apply -f ./api-pvc.yml
          kubectl apply -f ./db-deployment.yml
          kubectl apply -f ./api-deployment.yml
          kubectl apply -f ./db-service.yml
          kubectl apply -f ./api-service.yml
